### ISSUE TITLE
Convert URLs to HEX codes

### ISSUE THREAD

**Issue by Bluemoondragon07** [ALegendsTale/obsidian-color-palette#1]
Thank you so much for creating this plugin! I was just thinking two days ago, 「It'd be really nice if there was a plugin that could render HEX codes」, and here's a solution! Thank you so much!

One thing I thought of that could make this plugin even better is the ability to convert a code block with an URL to a code block with hex codes instead. That way, a code block dependent on an URL could quickly be made available offline. 

One can still manually copy the hex codes into a new code block, but a quick conversion would be really convenient.

Again, thank you for this awesome plugin and keep up the great work‼

**Comment by ALegendsTale** [comment]
Hey, thank you for the kind words and feedback! This change was included with the latest version [1.10](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/1.1.0)

**Comment by Bluemoondragon07** [comment]
Wow, that was fast! Thank you so much 🌟
