### ISSUE TITLE
now longer working in 1.5.12?

### ISSUE THREAD

**Issue by incantatem1** [ALegendsTale/obsidian-color-palette#11]
*no, not now, sorry

commands can no longer be accessed in this version. already existing color palettes are uneffected, individual palette codes can be copied and manually edited as well

**Comment by lunaria79** [comment]
Can confirm I am also experiencing this issue.

**Comment by ALegendsTale** [comment]
Hey, thanks for letting me know of this issue.

I had a look at a fresh install of 1.5.12 but couldn't seem to reproduce it. I was able to call commands from the command palette.

If you could provide the steps to reproduce the issue and the plugin version, I'll do my best to help.

**Comment by incantatem1** [comment]
hm, today it seems to be working again randomly? i didn't change anything though.... (installed 2 new themes but i doubt that fixed it, lol). weird, no idea what's going on.

**Comment by ALegendsTale** [comment]
Feel free to reopen this if the issue occurs again
