### ISSUE TITLE
2.12.0+ Canvas Bug with Plugin

### ISSUE THREAD

**Issue by SolemnVeilWeaver** [ALegendsTale/obsidian-color-palette#13]
Since 2.12.0, there has been a bug in canvas where the canvas disappears when dragging any item around. Took me a while to figure that it was this plugin that was causing it oddly enough. Reverting back to 2.11.0 doesn't have that issue and have reverted back to it for the time being.

**Comment by StefanDidak** [comment]
Can confirm this behavior. I was just about to come here to mention it and you beat me to it by two hours. :-)

**Comment by ALegendsTale** [comment]
Hello all, thanks for reporting this! It should be fixed in the [2.13.1](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.13.1).
