### ISSUE TITLE
how can i use Convert codeblock link to hex

### ISSUE THREAD

**Issue by chenbihao** [ALegendsTale/obsidian-color-palette#14]
What dose "codeblock link" mean,

I want to turn rgb into hex

but "Error: Selected text is not a codeblock with alink."

Did I misinterpret this command ?

```palette
rgb(017,050,093)
rgb(054,080,131)
rgb(115,107,157)
rgb(183,131,175)
rgb(245,166,115)
rgb(252,219,114)
{"height": 80}
```

**Comment by ALegendsTale** [comment]
There is now [documentation](https://github.com/ALegendsTale/obsidian-color-palette/blob/main/documentation/Commands.md#convert-codeblock-link-to-hex) for this command.

This command is somewhat old and mostly deprecated at this point. The right click context menu should be useful for converting RGB into HEX. It can be done by creating the palette, then right clicking it, and then selecting `Convert to HEX`.

**Comment by chenbihao** [comment]
> There is now [documentation](https://github.com/ALegendsTale/obsidian-color-palette/blob/main/documentation/Commands.md?rgh-link-date=2024-07-10T22%3A00%3A08Z#convert-codeblock-link-to-hex) for this command.
> 
> This command is somewhat old and mostly deprecated at this point. The right click context menu should be useful for converting RGB into HEX. It can be done by creating the palette, then right clicking it, and then selecting `Convert to HEX`.

It's so cool...

I didn't find it before. I even wrote a quickadd script for this. 

Thanks developer.
