### ISSUE TITLE
documents with many color palettes are extremely laggy now

### ISSUE THREAD

**Issue by incantatem1** [ALegendsTale/obsidian-color-palette#15]
since one of the recent updates it's near impossible to scroll through documents with many color palettes. i have some documents with a large collection of palettes which are basically inaccessible now (tested with various themes, all have the same problem).

**Comment by incantatem1** [comment]
addition: seems to be happening mostly with bigger palettes that have more colors in them, although i can't say for sure

**Comment by ALegendsTale** [comment]
Hello, thank you for reporting this.

I've attempted to fix this issue in the [latest release](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.13.7), along with some general performance improvements.

If they are still unresponsive, try modifying the new Reload Delay setting. Larger numbers will help improve performance at the cost of responsiveness. The default is 5.

**Comment by incantatem1** [comment]
looks much better now, thanks for the tip as well!
