### ISSUE TITLE
Feature request: Option to copy hex code without #

### ISSUE THREAD

**Issue by W70SD** [ALegendsTale/obsidian-color-palette#16]
I'd like to request an option to copy the color hex code without the # at the beginning.

Now: Clicking the color #FFFFFF on the color palette copies "#FFFFFF" to the clipboard.
Request: Clicking the color #FFFFFF on the color palette copies "FFFFFF" to the clipboard.

Thanks for this nice plugin!

**Comment by ALegendsTale** [comment]
Hello,

I think this is a stellar idea, so I've gone ahead an implemented it in the latest version 2.14.0. There is a new setting called `ColorFormat` which can be changed to `value` for this functionality.

Thank you for the suggestion!
