### ISSUE TITLE
styles.css is missing in release 1.1.0

### ISSUE THREAD

**Issue by sritsky** [ALegendsTale/obsidian-color-palette#2]
Downloaded through Brat. Colours didn’t render, saw that styles.css was missing and manually added styles.css to the plugin folder.

Now everything is perfect. Thank you for this plugin! I have been waiting for exactly this functionality for ages :)

**Comment by ALegendsTale** [comment]
Thank you for letting me know! I seem to have missed adding the styles.css to the release binaries. It should be fixed now :)
