### ISSUE TITLE
Is it possible to create gradient color?

### ISSUE THREAD

**Issue by Sleepleeps** [ALegendsTale/obsidian-color-palette#3]
Hi, I find this plugin really helpful and have a question: Is it possible to create gradient colors?

**Comment by ALegendsTale** [comment]
Hey, sorry for the late reply! I plan on releasing this with the next update soon.

**Comment by Sleepleeps** [comment]
thank you!

**Comment by Sleepleeps** [comment]
Wow, you work so quickly! Impressive efficiency! I noticed the latest update and wanted to say a big thank you for adding gradient colors!
