### ISSUE TITLE
Color palette no longer showing all colors. 

### ISSUE THREAD

**Issue by gnosthi** [ALegendsTale/obsidian-color-palette#4]
Obsidian Version: 1.5.3
Installer Version: 1.5.3
Color Palette Version: 2.0.1

I am using the Color Palette plugin pretty extensively and recently found that the palettes are not rendering correctly.  
It appears that the latest version of color palette introduced some breaking changes. 
In my  case, I was using newline delimited color palette. 
```palette
#E4D00A
#808000
#80461B
#000000
#FFBF00
#5C4033
#FFFF00
#000000
```
Which will now only render the first color. 
After looking at the plugin page i see that you've moved the options from the options screen to be inline with the code block and change the color palette to be comma+space delimited. 
One I switched from line delimited to comma+space delimited, the palette renders correctly. 

Please deprecate features first and create an announcement page for breaking changes for future updates so that we have a chance to change our notes before the old way is no longer supported. 

Thank you.

**Comment by ALegendsTale** [comment]
Hello, I admit the breaking changes could have been presented more elegantly. I apologize for not deprecating them first with an announcement.

I'll look into adding the newline delimited color palette back with the next set of changes. It should be ready for release soon.
Thank you for your feedback.

**Comment by ALegendsTale** [comment]
I've just released a [version](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.1.0) with newline support included. Please let me know if you have any other feedback. I appreciate your interest in this project.
