### ISSUE TITLE
plugin disabling tooltips across the app?

### ISSUE THREAD

**Issue by Tofutush** [ALegendsTale/obsidian-color-palette#5]
When I enable this plugin, all tooltips -- when you hover over file explorer buttons, ribbon icons, and files and folders -- disappear. When I hover over them, nothing happens. Things get back to normal as soon as this plugin is disabled, so I assume this plugin might be the problem.

**Comment by ALegendsTale** [comment]
Thanks a lot for reporting this issue! I didn't realize that Obsidian already used the .tooltip class so the plugin was overriding the default settings. There will be a new release that resolves this.
