### ISSUE TITLE
Feature request: custom name labels

### ISSUE THREAD

**Issue by gummywubbins** [ALegendsTale/obsidian-color-palette#6]
The plugin is pretty cool. Thanks!

It'd be useful to be able to attach a custom text label to each color. Example:

```
#ff0000: alert
#f3e6c0: window trim
```

**Comment by ALegendsTale** [comment]
This is a great idea. I'll work on adding this.

**Comment by ALegendsTale** [comment]
Added this feature with the [latest release](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.2.0). Enjoy!

**Comment by gummywubbins** [comment]
Awesome! Thanks!
