### ISSUE TITLE
Color palette: height is not changed after changing data.json

### ISSUE THREAD

**Issue by vkhatuntsevv** [ALegendsTale/obsidian-color-palette#7]
so, i did not like the initial height for color palette and changed it in data.json. it was fine for some time, but then it suddenly changed back to 150, even though my data.json file still has 50px set
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/161768359/c9f2a363-1006-4b8b-8a50-95356da72fb0)

**Comment by ALegendsTale** [comment]
Which plugin version are you currently running? Versions before 2.0.0 had their settings defined in the data.json, but in [ 2.0.0](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.0.0) and after, they are now defined directly in the codeblock.

Example:

\`\`\`palette
#000, #FFF
{"height": 50}
\`\`\`

**Comment by vkhatuntsevv** [comment]
> Which plugin version are you currently running?
yeah, i run 2.2. any methods of changing the height for all the color palettes i am to make?

**Comment by vkhatuntsevv** [comment]
also (unrelated to this issue, but still): can i anyhow type in a color in Color Palette, but make it show the "name" of the color (literally just some word)?
![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/161768359/6d018c84-6c43-4d80-999a-9537dce5db7f)

i found it's in css code, in <span style="--palette color: #ffffff;">NAME</span>, but i dunno how to put it inside obsidian

**Comment by ALegendsTale** [comment]
> yeah, i run 2.2. any methods of changing the height for all the color palettes i am to make?

This isn't currently possible but I'll work on implementing it. Thanks for the suggestion

**Comment by ALegendsTale** [comment]
> also (unrelated to this issue, but still): can i anyhow type in a color in Color Palette, but make it show the "name" of the color (literally just some word)? ![image](https://private-user-images.githubusercontent.com/161768359/309959174-6d018c84-6c43-4d80-999a-9537dce5db7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTI3NTIsIm5iZiI6MTcxMDAxMjQ1MiwicGF0aCI6Ii8xNjE3NjgzNTkvMzA5OTU5MTc0LTZkMDE4Yzg0LTZjNDMtNGQ4MC05OTlhLTk1MzdkY2U1ZGI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxOTI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDdkN2Q1Y2M2NWRiNTdkY2UxNmRlZDY3N2RjZTE0ZTVmNWMwNjM2YTU3YWMyMGE1MTcwYjdlZWEzYzMyODQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.efxwxiMsjZd1VBD0Wy6FiIbZM8F2lTO2Giiz8IvcGks)

This is already a feature called "aliases" codeblock options. 
Example from readme:
<pre>
```palette
#fff, #000fff00
{"gradient": true, "aliases": ["white", "black"]}
```
</pre>

**Comment by ALegendsTale** [comment]
In the newest [release](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.3.0), default height for all palettes can now be adjusted directly in the plugin settings. It can also still manually be adjusted per codeblock.

Enjoy!

**Comment by vkhatuntsevv** [comment]
tysm!!
