### ISSUE TITLE
Feature request: More color representations supported by css styles

### ISSUE THREAD

**Issue by chenbihao** [ALegendsTale/obsidian-color-palette#8]
Can I request support for more color representations supported by css styles, such as RGB and HSL:

```css
#289aff;
rgb(40, 154, 255);
hsl(210, 100%, 58%);
```

Additionally, if the delimiter also supports `;` That's even better, than can directly copy the code block from the CSS source code

---

A little more greedy :

Maybe customize the render height?

---

Also, thank you to the author for sharing the plugin. 

Originally, I searched like directly previewing the color block color in VSCode. 

![image](https://github.com/ALegendsTale/obsidian-color-palette/assets/21167262/63b25f34-0339-48e3-9612-5ee0f2820a4e)

Finally, I found that your color palette plugin, which looks better!

**Comment by ALegendsTale** [comment]
> Can I request support for more color representations supported by css styles, such as RGB and HSL:
> 
> ```css
> #289aff;
> rgb(40, 154, 255);
> hsl(210, 100%, 58%);
> ```
> 
> Additionally, if the delimiter also supports `;` That's even better, than can directly copy the code block from the CSS source code

Palettes do support RGB & HSL through the `create` command (using the color picker). They aren't yet supported in the codeblocks though. I can look into this request, thanks.

**Comment by ALegendsTale** [comment]
> A little more greedy :
> 
> Maybe customize the render height?

Do you mean the render height of the Palettes? This can be set in options.
Example:
<pre>
```palette
#fff, #000fff00
{"height": 150}
```
</pre>

**Comment by chenbihao** [comment]
> > A little more greedy :再贪婪一点： 
> > Maybe customize the render height?也许自定义渲染高度？
> 
> Do you mean the render height of the Palettes? This can be set in options.你是说调色板的渲染高度吗？这可以在选项中设置。 Example:  范例：
> 
> ```palette
> #fff, #000fff00
> {"height": 150}
> ```

Yes, I didn’t pay attention to Optional Settings before

**Comment by ALegendsTale** [comment]
The latest [release](https://github.com/ALegendsTale/obsidian-color-palette/releases/tag/2.4.0) adds support for most CSS color formats. Semicolons are also supported in parenthesis formats (like RGB & HSL) but they are not required.

Enjoy!
