### ISSUE TITLE
Error Message when using coolors.co link

### ISSUE THREAD

**Issue by TypicalSadClown** [ALegendsTale/obsidian-color-palette#9]
"URL provided is not valid" pops up when submitting a coolors link. Colorhunt links work as expected.

**Comment by ALegendsTale** [comment]
Hello, thanks for reporting this. Could you provide the coolors link used so that I can attempt to replicate the issue?

**Comment by heatherpiper** [comment]
I am also experiencing this issue with coolors links. The link I'm trying to use is this: https://coolors.co/2c2423-1e5f7b-839199-64abbb-88cc67-a0713e-dc6bad-bd93f9-f2647c-edcb79
